#! /bin/bash

# Usage: phd [dir] [host name]
#
# eventually, it might be `phd run [app]` if phd gets more sophisticated

# default apache virtualhosts path
PHD_APACHE_VIRTUALHOSTS='/etc/apache2/phd-sites'
PHD_APACHE_CONFIG='/etc/apache2/apache2.conf'
PHD_APACHE_INCLUDE="Include $PHD_APACHE_VIRTUALHOSTS"
PHD_APACHE_VIRTUALHOST_TEXT='<VirtualHost *:80>
  ServerName $host
  DocumentRoot $dir/public
  PassengerAppRoot $dir
</VirtualHost>'

dir=$(dirname $1)
host=$2
app_name=$(basename $dir)
base=$host

if [[ ! "$host" =~ "." ]]; then
  base=$host
  host="$host.webbyapp.com"
fi

sudo mkdir -p /var/log/phd
sudo chown -R git:www-data /var/log/phd

echo ""
echo "----------------------------"
echo "  Webbynode git deployment "
echo "----------------------------"
echo ""


if [[ ! "$base" =~ "." ]]; then
  ip=`ifconfig | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`
  echo "Setting up DNS..."
  echo ""
  output=`curl -s http://stage.mywebby.info/api/yaml/webbyapp/$base/create?ip=$ip`
  name=`echo "$output" | sed -n -e 's/:name: \(.*\)/\1/p' | sed -n -e 's/\( *\)//p'`
  host="$name.webbyapp.com"
fi

echo "Deploying application $app_name as $host..."

configure_apache_vhost() {
  if [[ -f "$PHD_APACHE_VIRTUALHOSTS/$host" ]]; then
		echo 'Already configured'
	else
		PHD_APACHE_VIRTUALHOST_TEXT="echo \"$PHD_APACHE_VIRTUALHOST_TEXT\""
		eval "$PHD_APACHE_VIRTUALHOST_TEXT" > $PHD_APACHE_VIRTUALHOSTS/$host
		echo "$app_name=$host" >> /var/webbynode/app_mappings
	fi
}

# read .phdrc (for overrides)
if [[ -f ~/.phdrc ]]; then
	source ~/.phdrc
fi

# if [[ ! -f "$PHD_APACHE_VIRTUALHOSTS" ]]; then
#   echo "$PHD_APACHE_VIRTUALHOSTS hasn't been configured"
#   echo "It needs to be editable by the git user"  
# fi

if [[ -z "$dir" || -z "$host" ]]; then
	echo "Usage: phd [application's .git directory] [hostname]"
	exit
fi

if [[ -d "$dir/app" && -d "$dir/app/controllers" && -f "$dir/config/environment.rb" ]]; then
  echo "Configuring Rails application..."
  
  echo "  => Configuring apache vHost..."
  configure_apache_vhost

  echo "  => Configuring database..."
  config_app_db $app_name > /var/log/phd/config_db.log 2>&1
	
  if [[ ! -f "$dir/config/database.yml" ]]; then
    echo "  => Configuring database.yml..."
    sed "s/@app_name@/$app_name/g" /var/webbynode/templates/database.yml > $dir/config/database.yml
  fi

  cd $dir
  echo "  => Installing missing gems..."
  sudo rake gems:install > /var/log/phd/gems_install.log 2>&1
  
  echo "  => Migrating database..."
  rake db:migrate > /var/log/phd/db_migrate.log 2>&1

  sudo chown -R git:www-data * > /var/log/phd/chown.log 2>&1
  cd -
  
  echo ""
  echo "Restarting apache..."
  sudo /etc/init.d/apache2 restart > /var/log/phd/apache2_restart.log 2>&1

  echo ""
  echo "$app_name deployed successfully."
  if [[ ! "$base" =~ "." ]]; then
    echo ""
    echo "Created http://$host/"
  fi
  echo ""

else
  if [[ -f "$dir/config.ru" ]]; then
    echo "Configuring Rack application..."
    echo "  => Configuring apache vHost..."
    configure_apache_vhost

    echo "  => Configuring database..."
    config_app_db $app_name > /var/log/phd/config_db.log 2>&1

    echo ""
    echo "Restarting apache..."
    sudo /etc/init.d/apache2 restart > /var/log/phd/apache2_restart.log 2>&1

    echo ""
    echo "$app_name deployed successfully."
    if [[ ! "$base" =~ "." ]]; then
      echo ""
      echo "Created http://$name.webbyapp.com/"
    fi
    echo ""
  fi
fi
