#! /bin/bash

# Usage: phd [dir] [host name]
#
# eventually, it might be `phd run [app]` if phd gets more sophisticated

if [[ -z "$1" ]]; then
	echo "Usage: phd [application's .git directory] [hostname] [app_engine]"
	exit
fi

PHD_ROOT=/var/webbynode/phd

dir=$(dirname $1)
host=$2
app_name=$(basename $dir)
base=$host
app_engine=$3

if [[ ! "$host" =~ "." ]]; then
  base=$host
  host="$host.webbyapp.com"
fi

# read .phdrc (for overrides)
if [[ -f ~/.phdrc ]]; then
	source ~/.phdrc
fi

echo ""
echo "----------------------------"
echo "  Webbynode git deployment "
echo "----------------------------"
echo ""

if [[ -d "/opt/nginx" ]]; then
  echo "Nginx+Passenger webserver detected..."
  WEB_SERVER="nginx"
  WEB_SERVER_ROOT="/opt/nginx"
elif [[ -d '/etc/nginx' ]]; then
  echo "Nginx webserver detected..."
  WEB_SERVER="nginx"
  WEB_SERVER_ROOT="/etc/nginx"
else
  echo "Apache webserver detected..."
  WEB_SERVER="apache"
  WEB_SERVER_ROOT='/etc/apache2'
fi

if [[ "$WEB_SERVER" == "nginx" ]]; then
  # default nginx virtualhosts path
  PHD_VIRTUALHOSTS="$WEB_SERVER_ROOT/phd-sites"
  PHD_CONFIG="$WEB_SERVER_ROOT/conf/nginx.conf"
  PHD_INCLUDE="include $PHD_VIRTUALHOSTS/*;"
else
  # default apache virtualhosts path
  PHD_VIRTUALHOSTS='/etc/apache2/phd-sites'
  PHD_CONFIG='/etc/apache2/apache2.conf'
  PHD_INCLUDE="Include $PHD_VIRTUALHOSTS"
fi

PUSHAND_INSTALL_DIR=~/tmp

sudo mkdir -p /var/log/phd
sudo chown -R git:www-data /var/log/phd

if [[ ! "$base" =~ "." ]]; then
  ip=`ifconfig | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`
  echo "Setting up DNS..."
  echo ""
  output=`curl -s https://manager.webbynode.com/api/yaml/webbyapp/$base/create?ip=$ip`
  name=`echo "$output" | sed -n -e 's/:name: \(.*\)/\1/p' | sed -n -e 's/\( *\)//p'`
  host="$name.webbyapp.com"
fi

echo "Deploying application $app_name as $host..."

configure_apache_vhost() {
  if [[ -f "$PHD_VIRTUALHOSTS/$host" ]]; then
		echo '     Already configured!'
		return 1
	else
		PHD_VIRTUALHOST_TEXT="echo \"$PHD_VIRTUALHOST_TEXT\""
		eval "$PHD_VIRTUALHOST_TEXT" > $PHD_VIRTUALHOSTS/$host
		echo "$host" >> /var/webbynode/mappings/$app_name.conf
		return 0
	fi
}

configure_nginx_vhost() {
  if [[ -f "$PHD_VIRTUALHOSTS/$host" ]]; then
		echo '     Already configured!'
		return 1
	else
		PHD_VIRTUALHOST_TEXT="echo \"$PHD_VIRTUALHOST_TEXT\""
		eval "$PHD_VIRTUALHOST_TEXT" > $PHD_VIRTUALHOSTS/$host
		echo "$host" >> /var/webbynode/mappings/$app_name.conf
		return 0
	fi
}

configure_vhost() {
  echo "  => Configuring $WEB_SERVER vHost..."
  if [[ "$WEB_SERVER" == "nginx" ]]; then
    configure_nginx_vhost
  else
    configure_apache_vhost
  fi
  
  return $?
}

restart_webserver() {
  echo ""
  if [[ "$1" == "1" ]]; then
    echo "Restarting passenger..."
    mkdir -p tmp
    touch tmp/restart.txt > /var/log/phd/passenger_restart.log 2>&1
  else
    echo "Restarting $WEB_SERVER"
    if [[ "$WEB_SERVER" == "apache" ]]; then
      sudo /etc/init.d/apache2 restart > /var/log/phd/apache2_restart.log 2>&1
    else
      sudo /etc/init.d/nginx restart > /var/log/phd/nginx_restart.log 2>&1
    fi
  fi
}

if [[ ! -z "$app_engine" ]]; then
  if [[ ! -x "$PHD_ROOT/scripts/$appengine.sh" ]]; then
    echo "Missing support for engine: $appengine. Aborting."
    exit
  else
    . $PHD_ROOT/scripts/$app_engine.sh
  fi
else
  if [[ -d "$dir/app" && -d "$dir/app/controllers" && -f "$dir/config/environment.rb" ]]; then
    . $PHD_ROOT/scripts/rails.sh
  elif [[ -f "$dir/config.ru" ]]; then
    . $PHD_ROOT/scripts/rack.sh
  else
    echo "WARNING: Didn't detect what application engine you're using."
  fi
fi

echo ""
echo "$app_name deployed successfully."
if [[ ! "$base" =~ "." ]]; then
  echo ""
  echo "Created http://$host/"
fi
echo ""
