#! /bin/bash

if [[ -d "/opt/nginx" ]]; then
  echo "Nginx+Passenger webserver detected..."
  WEB_SERVER="nginx"
  WEB_SERVER_ROOT="/opt/nginx"
  WEB_SERVER_CONFIG="$WEB_SERVER_ROOT/conf"
elif [[ -d '/etc/nginx' ]]; then
  echo "Nginx webserver detected..."
  WEB_SERVER="nginx"
  WEB_SERVER_ROOT="/etc/nginx"
else
  echo "Apache webserver detected..."
  WEB_SERVER="apache"
  WEB_SERVER_ROOT='/etc/apache2'
fi

test -z "$WEB_SERVER_CONFIG" && WEB_SERVER_CONFIG="$WEB_SERVER_ROOT"

PHD_VIRTUALHOSTS='/var/webbynode/vhosts'

if [[ "$WEB_SERVER" == "nginx" ]]; then
  # default nginx virtualhosts path
  PHD_CONFIG="$WEB_SERVER_CONFIG/nginx.conf"
  PHD_INCLUDE="  include $PHD_VIRTUALHOSTS/*;"
else
  # default apache virtualhosts path
  PHD_CONFIG='/etc/apache2/apache2.conf'
  PHD_INCLUDE="Include $PHD_VIRTUALHOSTS"
fi

PUSHAND_INSTALL_DIR=~/tmp

# read .phdrc (for overrides)
if [[ -f ~/.phdrc ]]; then
	source ~/.phdrc
fi

if [[ ! -w "$PHD_CONFIG" ]]; then
	echo "Don't have permission to edit $PHD_CONFIG"
	exit
fi

if [[ -z "$( which git-receive-pack_original )" ]]; then
	echo "Installing PushAnd"
	mkdir -p $PUSHAND_INSTALL_DIR
	cd $PUSHAND_INSTALL_DIR
	git clone git://github.com/webbynode/pushand.git
	cd pushand
	sudo ./pushand_server_install
fi

if [[ ! -f "$PHD_VIRTUALHOSTS" ]]; then
	echo "Creating virtualhosts directory"
	mkdir -p $PHD_VIRTUALHOSTS
	chmod a+rw $PHD_VIRTUALHOSTS
fi

if [[ -z "$( grep '$PHD_INCLUDE' $PHD_CONFIG )" ]]; then
	echo "Including virtualhosts in configuration"
	echo "\n$PHD_INCLUDE" >> $PHD_CONFIG
fi

ln -s /var/webbynode/phd/phd /usr/bin/phd
