#! /bin/bash

# default nginx virtualhosts path
PHD_NGINX_VIRTUALHOSTS='/opt/nginx/phd-sites'
PHD_NGINX_CONFIG='/opt/nginx/conf/nginx.conf'
PHD_NGINX_INCLUDE="include $PHD_NGINX_VIRTUALHOSTS/*;"
PUSHAND_INSTALL_DIR=~/tmp

# read .phdrc (for overrides)
if [[ -f ~/.phdrc ]]; then
	source ~/.phdrc
fi

if [[ ! -w "$PHD_NGINX_CONFIG" ]]; then
	echo "Don't have permission to edit $PHD_NGINX_CONFIG"
	exit
fi

if [[ -z "$( which git-receive-pack_original )" ]]; then
	echo "Installing PushAnd"
	mkdir -p $PUSHAND_INSTALL_DIR
	cd $PUSHAND_INSTALL_DIR
	git clone git://github.com/webbynode/pushand.git
	cd pushand
	sudo ./pushand_server_install
fi

if [[ ! -f "$PHD_NGINX_VIRTUALHOSTS" ]]; then
	echo "Creating virtualhosts directory"
	mkdir -p $PHD_NGINX_VIRTUALHOSTS
	chmod a+rw $PHD_NGINX_VIRTUALHOSTS
fi

if [[ -z "$( grep '$PHD_NGINX_INCLUDE' $PHD_NGINX_CONFIG )" ]]; then
	echo "Including virtualhosts in configuration"
	echo $PHD_NGINX_INCLUDE >> $PHD_NGINX_CONFIG
fi
